import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/nabver/Navbar";
// import SignIn from '../Components/LoginForm/SignIn/page'
import Side from '../app/sidebar/side'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-400 `}
      >
      {/* <div className="grid grid-col-2"> */}
        {/* <nav className=" flex w-full">
          */}
         <Navbar/>
          {/* <Side/> */}
          {/* <ul className=" max-sm:mr-6 flex  rounded-md shadow shadow-sky-700 w-full h-20 bg-slate-50 text-violet-800 font-serif  ">
            <span className=" mt-6 gap-2 bg-sky-30 rounded-lg ">
            <Link href="/">  <li className="shadow-md hover:shadow-violet-300 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110 hover:bg-violet-500 duration-150  bg-violet-400 mx-2 rounded-md px-2 py-[2px] " >Home</li> </Link>
            <Link href="/About">  <li className="shadow-md hover:shadow-violet-300 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110 hover:bg-violet-500 duration-150  bg-violet-400 mx-2 rounded-md px-2 py-[2px] ">About</li> </Link>
            <Link href="/Blog">  <li className="shadow-md hover:shadow-violet-300 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110 hover:bg-violet-500 duration-150  bg-violet-400 mx-2 rounded-md px-2 py-[2px] ">Blog</li > </Link>
            <Link href="/posts">  <li className="shadow-md hover:shadow-violet-300 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110 hover:bg-violet-500 duration-150  bg-violet-400 mx-2 rounded-md px-2 py-[2px] ">Posts</li> </Link>
            <Link href="/Login">  <li className="shadow-md hover:shadow-violet-300 transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110 hover:bg-violet-500 duration-150  bg-violet-400 mx-2 rounded-md px-2 py-[2px] ">Login</li> </Link>
            </span>
          </ul> */}
        {/* </nav> */}
        {/* </div> */}
        <hr />
        {children}
      </body>
    </html>
  );
}
